# Generated by Django 5.0.2 on 2024-02-10 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyek', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyek',
            old_name='tanggal_selesai',
            new_name='estimasi_selesai',
        ),
    ]
