# Generated by Django 5.0.2 on 2024-02-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyek', '0002_rename_tanggal_selesai_proyek_estimasi_selesai'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyek',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('HOLD', 'Hold'), ('DONE', 'Done')], default='Not Started', max_length=20),
        ),
    ]
