# Generated by Django 5.0.2 on 2024-02-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyek', '0003_proyek_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyek',
            name='estimasi_selesai',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyek',
            name='tanggal_mulai',
            field=models.DateField(),
        ),
    ]
