# Generated by Django 5.0.2 on 2024-02-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0002_tugas_proyek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tugas',
            name='estimate_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
