# Generated by Django 5.0.2 on 2024-02-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0003_alter_tugas_estimate_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tugas',
            name='estimate_time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
