# Generated by Django 5.0.2 on 2024-02-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0004_alter_tugas_estimate_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tugas',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('HOLD', 'Hold'), ('DONE', 'Done')], default='Not Started', max_length=20),
        ),
    ]
