# Generated by Django 5.0.2 on 2024-02-11 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0005_alter_tugas_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tugas',
            old_name='proyek',
            new_name='proyek_id',
        ),
    ]
